### ISSUE TITLE
Decidim Update 0.27

### ISSUE THREAD

**Issue by larsUE** [puzzle/decidim-zuerich#151]
Precondition-Checklist:
 **Module**
- [x]  decidim-proposals (Als Teil des Decidim Projekts aktualisiert)
- [x]   decidim-conferences (Als Teil des Decidim Projekts aktualisiert)
- [ ]   decidim-anonymous_proposals (Wurde im ursprünglichen Projekt aktualisiert)
- [x]   decidim-decidim_awesome (PR gemerged, Release folgt in den nächsten Tagen)
- [x]   decidim-term_customizer

_Derzeit sowieso nicht aktivierte Module:_
- [ ]   decidim-url_aliases
- [ ]   decidim-navigation_maps (Platoniq)
- [ ]   decidim-homepage_interactive_map (OpenSourcePolitics)

Bekannte Seiten, die bereits auf V0.27 sind:
- [meta.decidim](https://meta.decidim.org)

**Comment by larsUE** [comment]
@Kagemaru FYI: Ich habe nochmals nachgeschaut und der Term Customizer ist auch bereits auf Version 0.27 :) Es fehlt noch das anonymous Modul, aber von dem gabs auch nie ein Update auf 26 und es läuft dennoch gut -> könnte also wieder klappen. Auf alle Fälle können wir also mit dem Update loslegen, sobald wir mit der Übersetzung durch sind.

**Comment by Kagemaru** [comment]
@larsUE 
> Es fehlt noch das anonymous Modul, aber von dem gabs auch nie ein Update auf 26 und es läuft dennoch gut

Das stimmt leider nicht ganz. Wir hatten damals das Repo geforkt und bei uns die Versionen erhöht. In der Zwischenzeit gibt es von ihnen auch einen `release/0.26-stable` branch, den wir nun auch benutzen.
Beim Upgrade auf 0.27 funktioniert dies bedauerlicherweise oft nicht, da viele zentrale Elemente von Decidim geändert haben.

Ich probiere es trotzdem mal.

**Comment by larsUE** [comment]
Testing notes Lars:

### Modules
- [x] Anonymous proposals
- [x] Decidim Awesome
- [x] term customizer

### Eigene Weiterentwicklungen
- [ ] URL Weiterleitungen: funktioniert nicht, siehe #376 
- [x] Umfrage Dropdowns und Sorts

### Component-Tests
- [ ] Meetings funktionieren nicht, siehe #374 
- [ ] Geolocation: Pins werden nich angezeigt, siehe #375 

### Other
- [ ] Profileinstellungen crashen, siehe #373

**Comment by larsUE** [comment]
Ich close hier mal, da wir einzelne Bugs über individuelle Tickets mit den Tags "Update" und "Bug" lösen.
